### ISSUE TITLE
特征选择问题

### ISSUE THREAD

**Issue by z1ouhan** [wujiekd/Predicting-used-car-prices#7]
Hello，看了您的文档里面有写“直接使用 lightgbm 帮我们去选择特征，一组组的放进去”具体做法是怎样呢？
例如：brand和price特征交叉之后这组新的特征加上原来的特征放进lightgbm训练过后，看feature_importance吗？

刚开始学习数据挖掘相关工作，期待您的回复

**Comment by wujiekd** [comment]
其实就是放进去跑一轮，看验证集的分数有没有提升~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wujiekd/Predicting-used-car-prices"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 晚上6:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wujiekd/Predicting-used-car-prices] 特征选择问题 (Issue #7)





 
Hello，看了您的文档里面有写“直接使用 lightgbm 帮我们去选择特征，一组组的放进去”具体做法是怎样呢？
 例如：brand和price特征交叉之后这组新的特征加上原来的特征放进lightgbm训练过后，看feature_importance吗？
 
刚开始学习数据挖掘相关工作，期待您的回复

**Comment by z1ouhan** [comment]
感谢解答！这样操作的工程量有点大啊😮

**Comment by wujiekd** [comment]
测试特征时，一组组的放进去，单个微调确实麻烦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wujiekd/Predicting-used-car-prices"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 晚上7:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wujiekd/Predicting-used-car-prices] 特征选择问题 (Issue #7)





 
感谢解答！这样操作的工程量有点大啊😮
